version: "3"

services:
  mongodb:
    container_name: auth_mongo
    image: mongo
    ports:
      - "27017:27017"
  app:
    container_name: auth
    build: .
    ports:
      - "8000:8000"
    links:
      - mongodb
